### ISSUE TITLE
Cannot access wintersmiths content tree inside nunjucks template

### ISSUE THREAD

**Issue by lutzer** [jbuck/wintersmith-nunjucks#24]
Hi,

I can't figure out how to access the content tree within an nunjucks template. 

Could anyone provide me an example on how to print the list of articles of the blog example from the wintersmith page?

i thought something like this might work:

```
{% for article in contents.articles %}
  		<div class="article-item">
  			<h2> An Article </h2>
  		</div>
{% endfor %}
```

but the articles list seems to be empty. Any Idea on this?

**Comment by lutzer** [comment]
oh, i found the solution now. but it took me some time. wintersmith doesnt order the articles in an array, but in a json object.

this code works:

```
{% for slug,article in contents.articles %}
        <div class="article-item">
            <h2>{{ slug }}</h2>
        </div>
{% endfor %}
```

**Comment by jbuck** [comment]
Excellent, glad you were able to figure it out!
